//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anna.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anna.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry sort.
        /// </summary>
        internal static string DialogTitle_EntrySort {
            get {
                return ResourceManager.GetString("DialogTitle_EntrySort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Attribute.
        /// </summary>
        internal static string EntrySort_Mode_Attribute {
            get {
                return ResourceManager.GetString("EntrySort_Mode_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extension.
        /// </summary>
        internal static string EntrySort_Mode_Extension {
            get {
                return ResourceManager.GetString("EntrySort_Mode_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name.
        /// </summary>
        internal static string EntrySort_Mode_Name {
            get {
                return ResourceManager.GetString("EntrySort_Mode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File size.
        /// </summary>
        internal static string EntrySort_Mode_Size {
            get {
                return ResourceManager.GetString("EntrySort_Mode_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Timestamp.
        /// </summary>
        internal static string EntrySort_Mode_Timestamp {
            get {
                return ResourceManager.GetString("EntrySort_Mode_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ascending.
        /// </summary>
        internal static string EntrySort_Order_Ascending {
            get {
                return ResourceManager.GetString("EntrySort_Order_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Descending.
        /// </summary>
        internal static string EntrySort_Order_Descending {
            get {
                return ResourceManager.GetString("EntrySort_Order_Descending", resourceCulture);
            }
        }
    }
}
