//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anna.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anna.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anna.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All &amp;delete.
        /// </summary>
        public static string Dialog_AllDelete {
            get {
                return ResourceManager.GetString("Dialog_AllDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _trash can.
        /// </summary>
        public static string Dialog_OpenTrashCan {
            get {
                return ResourceManager.GetString("Dialog_OpenTrashCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Retry.
        /// </summary>
        public static string Dialog_Retry {
            get {
                return ResourceManager.GetString("Dialog_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Skip.
        /// </summary>
        public static string Dialog_Skip {
            get {
                return ResourceManager.GetString("Dialog_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change entry name.
        /// </summary>
        public static string DialogTitle_ChangeEntryName {
            get {
                return ResourceManager.GetString("DialogTitle_ChangeEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        public static string DialogTitle_Compress {
            get {
                return ResourceManager.GetString("DialogTitle_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy entry.
        /// </summary>
        public static string DialogTitle_CopyEntry {
            get {
                return ResourceManager.GetString("DialogTitle_CopyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        public static string DialogTitle_CreateFile {
            get {
                return ResourceManager.GetString("DialogTitle_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string DialogTitle_CreateFolder {
            get {
                return ResourceManager.GetString("DialogTitle_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress.
        /// </summary>
        public static string DialogTitle_Decompress {
            get {
                return ResourceManager.GetString("DialogTitle_Decompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry.
        /// </summary>
        public static string DialogTitle_DeleteEntry {
            get {
                return ResourceManager.GetString("DialogTitle_DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump folder.
        /// </summary>
        public static string DialogTitle_JumpFolder {
            get {
                return ResourceManager.GetString("DialogTitle_JumpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move entry.
        /// </summary>
        public static string DialogTitle_MoveEntry {
            get {
                return ResourceManager.GetString("DialogTitle_MoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string DialogTitle_Rename {
            get {
                return ResourceManager.GetString("DialogTitle_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select copy action.
        /// </summary>
        public static string DialogTitle_SelectFileCopyAction {
            get {
                return ResourceManager.GetString("DialogTitle_SelectFileCopyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string DialogTitle_SelectFolder {
            get {
                return ResourceManager.GetString("DialogTitle_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort entry.
        /// </summary>
        public static string DialogTitle_SortEntry {
            get {
                return ResourceManager.GetString("DialogTitle_SortEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFile.
        /// </summary>
        public static string Entry_NewFile {
            get {
                return ResourceManager.GetString("Entry_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFolder.
        /// </summary>
        public static string Entry_NewFolder {
            get {
                return ResourceManager.GetString("Entry_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings....
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Anna....
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort entry....
        /// </summary>
        public static string Menu_View_SortEntry {
            get {
                return ResourceManager.GetString("Menu_View_SortEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Access denied..
        /// </summary>
        public static string Message_AccessDenied {
            get {
                return ResourceManager.GetString("Message_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///The operation cannot be completed because the folder or file may be open in another program.
        ///Please close the folder or file and retry the operation..
        /// </summary>
        public static string Message_AccessFailureOnDelete {
            get {
                return ResourceManager.GetString("Message_AccessFailureOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary files cannot be previewed..
        /// </summary>
        public static string Message_BinaryFileCannotBePreviewed {
            get {
                return ResourceManager.GetString("Message_BinaryFileCannotBePreviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Do you want to delete this?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start associated app..
        /// </summary>
        public static string Message_FailedToStartAssociatedApp {
            get {
                return ResourceManager.GetString("Message_FailedToStartAssociatedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Failed to start editor.
        ///The editor is not registered or does not exist..
        /// </summary>
        public static string Message_FailedToStartEditor {
            get {
                return ResourceManager.GetString("Message_FailedToStartEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder already contains a file with the same name..
        /// </summary>
        public static string Message_FolderAlreadyContainsSameName {
            get {
                return ResourceManager.GetString("Message_FolderAlreadyContainsSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new name..
        /// </summary>
        public static string Message_InputNewName {
            get {
                return ResourceManager.GetString("Message_InputNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omitted due to large size..
        /// </summary>
        public static string Message_OmittedDueToLargeSize {
            get {
                return ResourceManager.GetString("Message_OmittedDueToLargeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///This entry is read-only. Do you want to delete it?.
        /// </summary>
        public static string Message_ReadOnlyConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ReadOnlyConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entries exist in the trash can.
        ///Do you want to delete them completely?.
        /// </summary>
        public static string Messege_ConfirmEmptyTrashCan_Multi {
            get {
                return ResourceManager.GetString("Messege_ConfirmEmptyTrashCan_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entry exist in the trash can.
        ///Do you want to delete it completely?.
        /// </summary>
        public static string Messege_ConfirmEmptyTrashCan_Single {
            get {
                return ResourceManager.GetString("Messege_ConfirmEmptyTrashCan_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att_ribute.
        /// </summary>
        public static string SortEntry_Mode_Attribute {
            get {
                return ResourceManager.GetString("SortEntry_Mode_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extension.
        /// </summary>
        public static string SortEntry_Mode_Extension {
            get {
                return ResourceManager.GetString("SortEntry_Mode_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name.
        /// </summary>
        public static string SortEntry_Mode_Name {
            get {
                return ResourceManager.GetString("SortEntry_Mode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File size.
        /// </summary>
        public static string SortEntry_Mode_Size {
            get {
                return ResourceManager.GetString("SortEntry_Mode_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Timestamp.
        /// </summary>
        public static string SortEntry_Mode_Timestamp {
            get {
                return ResourceManager.GetString("SortEntry_Mode_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ascending.
        /// </summary>
        public static string SortEntry_Order_Ascending {
            get {
                return ResourceManager.GetString("SortEntry_Order_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Descending.
        /// </summary>
        public static string SortEntry_Order_Descending {
            get {
                return ResourceManager.GetString("SortEntry_Order_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _overwrite.
        /// </summary>
        public static string UI_CopyOverride {
            get {
                return ResourceManager.GetString("UI_CopyOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy when timestamp is _newest.
        /// </summary>
        public static string UI_CopyWhenTimestampIsNewest {
            get {
                return ResourceManager.GetString("UI_CopyWhenTimestampIsNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UI_Edit {
            get {
                return ResourceManager.GetString("UI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Folder....
        /// </summary>
        public static string UI_JumpFolderDialog {
            get {
                return ResourceManager.GetString("UI_JumpFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UI_Name {
            get {
                return ResourceManager.GetString("UI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string UI_Path {
            get {
                return ResourceManager.GetString("UI_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename and copy.
        /// </summary>
        public static string UI_RenameAndCopy {
            get {
                return ResourceManager.GetString("UI_RenameAndCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same _action thereafter.
        /// </summary>
        public static string UI_SameActionThereafter {
            get {
                return ResourceManager.GetString("UI_SameActionThereafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To _Trash can.
        /// </summary>
        public static string UI_ToTrashCan {
            get {
                return ResourceManager.GetString("UI_ToTrashCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists..
        /// </summary>
        public static string Validation_ExistsEntry {
            get {
                return ResourceManager.GetString("Validation_ExistsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains characters cannot be used..
        /// </summary>
        public static string Validation_NameContainsCharacterCannotBeUsed {
            get {
                return ResourceManager.GetString("Validation_NameContainsCharacterCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same name is entered..
        /// </summary>
        public static string Validation_SameName {
            get {
                return ResourceManager.GetString("Validation_SameName", resourceCulture);
            }
        }
    }
}
